"""empty message

Revision ID: 585a7a02ba63
Revises: e0c2ff5f7598
Create Date: 2025-01-26 21:20:44.262653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'Add question table'
down_revision: Union[str, None] = 'e0c2ff5f7598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.create_table(
        'question',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['category_id'], ['category.id']),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('vote')
    op.drop_table('notification')
    op.drop_table('question_tag')
    op.drop_table('tag')
    op.drop_table('question')
    op.drop_table('content')
    # ### end Alembic commands ###
