"""empty message

Revision ID: 2bf66b12ce10
Revises: 585a7a02ba63
Create Date: 2025-01-26 21:21:15.422661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'Add content table'
down_revision: Union[str, None] = '585a7a02ba63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    op.create_table(
        'content',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('creation_time', sa.DateTime(), nullable=False),
        sa.Column('last_update_time', sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('question_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.ForeignKeyConstraint(['question_id'], ['question.id']),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'answer_id')
    op.drop_table('vote')
    op.drop_table('notification')
    op.drop_table('question_tag')
    op.drop_table('tag')
    op.drop_table('content')
    # ### end Alembic commands ###
