"""empty message

Revision ID: e0c2ff5f7598
Revises: 
Create Date: 2025-01-26 21:20:11.436809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'Init without depends table'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    def upgrade():
        op.create_table(
            'category',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_table(
            'role',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('role_name', sa.String(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_table(
            'user',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('email', sa.String(), nullable=False),
            sa.Column('hashed_password', sa.String(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('vote')
    op.drop_table('notification')
    op.drop_table('question_tag')
    op.drop_table('tag')
    op.drop_table('question')
    op.drop_table('content')
    # ### end Alembic commands ###
